name: Test Action

on:
  push:
    branches:
      - main  # Triggers the workflow on push to "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Email
        run: echo "User email: 22f3000356@ds.study.iitm.ac.in"
